### PR TITLE
Topaz marketplace parsing 

### PR DESCRIPTION
**Pull request by rtso**
## Stack Description
Create a processor as a replacement for the [NFT_ORDERBOOK pipeline](https://github.com/aptos-labs/internal-ops/blob/main/pipelines/indexer_analytics/models/nft_orderbook/NFT_ORDERBOOK.sql). This data is used to power the [NFT Aggregated Orderbook dashboard](https://aptoslabs.cloud.looker.com/dashboards/22?Transaction%20Date=180%20day&Collection%20Name=Aptomingos). 

## PR Description 
Adds parsing for Topaz listing, token bids, and collection bids. This PR shows how the parsing will be done for all marketplaces, using Topaz as the example. Parsing for the rest of the marketplaces will be come in the next PRs.

## Data model 
[NFT Orderbooks data model](https://docs.google.com/spreadsheets/d/15GdG0u-Bl-SfdRlBvYimbgjXn76kbVm1IbBUYuHCIBg/edit#gid=0)

* current_nft_marketplace_listings
   * can be used to calculate current floor prices of a collection, current liquidity
* nft_marketplace_listings, nft_marketplace_bids, nft_marketplace_collection_bids
   * can be used to calculate liquidity over time
* current_nft_marketplace_bids, current_nft_marketplace_collection_bids
   * can be used to calculate current liquidity

## DQ Checks
Total liquidity match for every event type
| nft_orderbooks | Processor |
|--------|--------|
| Screenshot 2023-06-12 at 8 06 40 PM | nft_marketplace_listings Screenshot 2023-06-12 at 8 07 03 PM
| | nft_marketplace_bids Screenshot 2023-06-12 at 8 06 55 PM |
| | nft_marketplace_collection_bids Screenshot 2023-06-12 at 8 06 47 PM |

### CODE REVIEW

**Comment by bowenyang007** [comment]
Sorry can you add a bit more context as to why we're doing this just for topaz? Is this going to be used somewhere?

**Comment by rtso** [comment]
@bowenyang007 I updated the description but basically this PR is showing how parsing write set changes will look like for one marketplace. Parsing for the rest of the marketplaces will be done in the next PR.

**Comment by rtso** [comment]
@bowenyang007 added DQ checks

**Comment by bowenyang007** [comment]
This makes sense! Thanks for doing the due diligence. I'm not sure 100% if the data model is the final one but we can always update. Great work!

**Pull request merged**
