### PR TITLE
test cross repo ci trigger

### PR DESCRIPTION
**Pull request by yuunlimm**

### CODE REVIEW

**Comment by larry-aptos** [comment]
looks good; do we want to merge? or you will include more changes?

**Comment by yuunlimm** [comment]
> looks good; do we want to merge? or you will include more changes?

I would just like to make sure that it's trigger first, then we can remove this and modify the existing one!

**Comment by larry-aptos** [comment]
lol the aggressive linter

**Comment by yuunlimm** [comment]
will use temp public repo to test

**Pull request closed without merging**
